# Generated by Django 4.1.7 on 2023-02-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('name_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_products', models.ManyToManyField(blank=True, to='products.product')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.server')),
            ],
        ),
    ]
